import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50">
        <header className="bg-blue-600 text-white shadow-md">
          <nav className="container mx-auto px-4 py-4">
            <ul className="flex space-x-6">
              <li><a href="/" className="hover:underline font-medium">Home</a></li>
              <li><a href="/products" className="hover:underline font-medium">Products</a></li>
              <li><a href="/products/categories" className="hover:underline font-medium">Categories</a></li>
              <li><a href="/users" className="hover:underline font-medium">Users</a></li>
            </ul>
          </nav>
        </header>
        <main className="container mx-auto px-4 py-8">
          {children}
        </main>
      </body>
    </html>
  )
}
